language: python

python:
- '3.4'
- '3.5'
- '3.6'

install:
- pip install -r requirements/arthash_requirements.txt
- pip install -r requirements/arthashd_requirements.txt
- pip install -r requirements/test_requirements.txt

script:
- flake8
- pytest
